#!/usr/bin/env sh

node scripts/ensure-deps.js || exit 1
npm run format:check || exit 1
npm run lint || exit 1
npm run typecheck || exit 1
npm run test || exit 1
npm run build || exit 1
npm run validate:dist || exit 1
